### ISSUE TITLE
Selection color barely visible

### ISSUE THREAD

**Issue by winterbe** [sindresorhus/terminal-snazzy#2]
Heya,

thanks for this theme, it's awesome. However I noticed a minor annoyance. The selection color is barely visible.

Example:

![bildschirmfoto 2018-08-09 um 10 10 34](https://user-images.githubusercontent.com/485033/43886646-adfded10-9bbc-11e8-8d51-ce07abba1547.png)

On this screenshot `jest.klett.json` is marked but the color is barely visible because contrast to background is too low.

I've tried to fix it myself, but I don't have a clue how the color is actually encoded:

```
	<key>SelectionColor</key>
	<data>
	YnBsaXN0MDDUAQIDBAUGFRZYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3AS
	AAGGoKMHCA9VJG51bGzTCQoLDA0OVU5TUkdCXE5TQ29sb3JTcGFjZVYkY2xhc3NPECcw
	LjE2NzAwMTYxMTYgMC4xODA4MDM3ODI5IDAuMjMwMTMwNTUzMgAQAYAC0hAREhNaJGNs
	YXNzbmFtZVgkY2xhc3Nlc1dOU0NvbG9yohIUWE5TT2JqZWN0XxAPTlNLZXllZEFyY2hp
	dmVy0RcYVHJvb3SAAQgRGiMtMjc7QUhOW2KMjpCVoKmxtL3P0tcAAAAAAAABAQAAAAAA
	AAAZAAAAAAAAAAAAAAAAAAAA2Q==
	</data>
```

Tested on MacOS 10.13.6 with native Terminal.app.

**Comment by winterbe** [comment]
I was too lazy recognizing that you can simply override selection color in terminal settings.

Never mind. 🍻

**Comment by sholladay** [comment]
@sindresorhus is this something you'd be willing to fix in the theme? I duplicated the theme and tweaked the selection color so it's more visible for me but it would be nice to have it be visible out of the box.

**Comment by sindresorhus** [comment]
PR welcome :)
